#! /bin/sh

# Wrapper for VFS test programs.  It makes sure the modules are loaded
# from the build directory instead of the system one.

GNOME_VFS_MODULE_PATH=/home/qwazix/cordia/gnome-vfs-2.24.4/modules/.libs
export GNOME_VFS_MODULE_PATH

echo "VFS modules will be loaded from $GNOME_VFS_MODULE_PATH"

PATH=.:$PATH
export PATH

exec $@

echo "$0: cannot exec "$@
